### ISSUE TITLE
Failed to add deploy keys on GitHub

### ISSUE THREAD

**Issue by statnmap** [ropenscilabs/travis#105]
I used `tic::use_tic()` to deploy the pkgdown site of my package but I got this error:
```
Error in remove_key_if_exists(key_data, repo, gh_token, quiet) : 
  Not Found (HTTP 404). Failed to query deploy keys on GitHub for repo ThinkR-open/checkhelper.
```
The repository is a company repository but I must say I have the owner access to this repository.
I started to debug the function and found out that the problem is in `travis::use_travis_deploy()` function.  Both `remove_key_if_exists` and `github_add_key` do not work.

 If I go further inside `github_add_key` function, I found that `ret <- add_key(key_data, repo, gh_token, quiet)` is not working with error:
```
Error in check_status(req, sprintf("ad[ding]{d} deploy keys on GitHub for repo %s",  : 
  Not Found (HTTP 404). Failed to add deploy keys on GitHub for repo ThinkR-open/checkhelper.
```

I assume that the GITHUB_POST on line https://github.com/ropenscilabs/travis/blob/cfa0a2b5c15532479dab06e843de7757a8de1338/R/github-key.R#L99 is at the origin of the problem.  

I did the operation manually on Github website and it works.

I use {travis} v0.2.11.9000 and {httr} v1.4.1

**Comment by pat-s** [comment]
Everything working for orgs on my side with `travis::use_travis_deploy()`.

Did you by chance try with a fork instead of a normal repo? We just had a similar issue in which this was the problem.

**Comment by statnmap** [comment]
Thanks for your answer.  
This is not a fork. I tried with another repository in the organization account but it does not work.  However, I tried with a repo on my own account and it works.  
I am admin in the organisation account (https://github.com/ThinkR-open), so it do not understand where I am blocked.

**Comment by pat-s** [comment]
Maybe it comes down to repository rights/team memberships? This is not easy to debug because we cannot simply create a reprex here.

Can you give yourself explicit write permissions in the repo, maybe even using "Teams" in the organization? IIRC all my organizations are set up like this. Maybe being the organization owner is not enough? Would be interesting to find out.

I am positive that there should be a way to make this work for you.

**Comment by statnmap** [comment]
I added me inside a Team as well as collaborator. Independently or combined, this has no effect.  
![image](https://user-images.githubusercontent.com/21193866/63347848-501b1000-c358-11e9-946d-e7529bbe0dc3.png)

Obviously, I already had the privilege to create a deploy key as I did it interactively, but I can't with the API. This must be somewhere else...

**Comment by pat-s** [comment]
Thanks for trying!

Would it be possible to create a test repo within your org and add me as a collab? So I could try things on my own?

**Comment by statnmap** [comment]
Sure.
Here is the repo: https://github.com/ThinkR-open/test-repo  
You may have received an invitation. I added you as maintainer. Do know what it means exactly in terms of settings permissions

**Comment by pat-s** [comment]
Thanks. This does not seem to be enough yet, I get the following:

> Error: Must have role admin to add deploy key to repo ThinkR-open/test-repo, not write

**Comment by statnmap** [comment]
I added you in a team, the team being Admin of the repo.  
You'll probably have to accept the invitation to the team.

**Comment by pat-s** [comment]
Ok. So the problem seems to be that https://api.github.com/repos/ThinkR-open/test-repo/keys returns a 404 in

https://github.com/ropenscilabs/travis/blob/cfa0a2b5c15532479dab06e843de7757a8de1338/R/github-key.R#L75-L78

whereas trying it with `ropenscilabs/tic.package` returns a valid 200 return code.

I just created a new test org with a new repo and getting the same 404 error there.
At first I suspected that we may run in trouble if there is no existing key yet and therefore the http request returns 404 (which actually shouldn't happen).
So I added one manually but that did not change anything, still getting a 404.
I was thinking about different permissions in some way between the orgs but could not come up with a difference.

I assume that something changed with for recent orgs within the Github API.

@krlmlr 	Do you have an idea what might be the problem here? Otherwise I would ask in the Github dev forum.

**Comment by pat-s** [comment]
It seems that it comes down to the rate [limit for API requests for a certain API](https://developer.github.com/v3/#rate-limiting).

Example

```
curl -i https://api.github.com/repos/giscience-fsu/hpc-user-guide/keys  

X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1569854123
```

Note the reset time (50 years). All of this is triggered by 

https://github.com/ropenscilabs/travis/blob/cfa0a2b5c15532479dab06e843de7757a8de1338/R/github-key.R#L75-L78

This means the behavior might differ if you use the function from a different IP/network.
AFAICS the `gh_token` we are passing has nothing to do with the rate limit but is only used for auth tasks.
If I use my local phone as a hotspot, I get "Not Found" when entering "https://api.github.com/repos/giscience-fsu/hpc-user-guide/keys" in the browser and when using `GITHUB_GET` from above.

To solve this, one can [pass an app's client ID with the query](https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications).
Also see [this SO question](https://stackoverflow.com/questions/44395747/github-api-limit-exceeded-how-to-increase-the-rate-limit-in-front-end-apps#46835353).

---

I just found that when we replace `GITHUB_GET` above by [`gh::gh()`](https://github.com/r-lib/gh), the request succeeds.
I guess it would simplify things it we outsource all the GH requests to the _gh_ package.
I do not know what they do different in terms of API requests and limits but I am also not an expert in these things.

**Comment by pat-s** [comment]
@statnmap Can you try `use_travis_deploy()` or `tic::use_tic()` with the `gh` branch of this package? I.e. installing `remotes::install_github("ropenscilabs/travis@gh")`.

It is a bare bone change only which worked for another org of mine.

**Comment by statnmap** [comment]
Yes this works !    
_But you let a `browser()` call in `github_add_key()`:_ https://github.com/ropenscilabs/travis/blob/6f6e0388f1a99390dddb741953f1f51bdb057847/R/github-key.R#L45

**Comment by pat-s** [comment]
Cool! Then I'll continue on this.

> But you let a browser() call in github_add_key():

Ups, well spotted! :)
