### ISSUE TITLE
Reduce the tabs opened with `use_travis_deploy`

### ISSUE THREAD

**Issue by llrs** [ropenscilabs/travis#108]
`travis::use_travis_deploy()` opens three tabs on my default browser. Could it open just one?

My workflow:
```r
usethis::use_pkgdown()
usethis::use_pkgdown_travis()
travis::use_travis_deploy() # Following the advice of the previous command.
```
This last command opens three tabs on my browser. While I expect it to be opened at most 1. I don't know enough of the code to suggest a PR. Probably it is related to #97

**Comment by pat-s** [comment]
> This last command opens three tabs on my browser. While I expect it to be opened at most 1.

Why do you expect only one?

**Comment by llrs** [comment]
Because I only want one thing, to have my webpage as a github page. This would be just one permission to read from the repository and maybe one to write to the docs. But isn't it possible to make it in just one API call?

BTW, In the help page it doesn't explain what it returns...

**Comment by pat-s** [comment]
> Because I only want one thing, to have my webpage as a github page.
> age.

And this procedure requires more than just one step :)

In the description of the function it lists three things:

1. Creates a public-private key pair
1. adds the public key to the GitHub repository via github_add_key()
1. stores the private key as an encrypted environment variable in Travis CI via travis_set_var(), possibly in a different repository. 

Idk whether all of the three trigger exactly one browser window but since they are run sequentially, I don't know how this should be done in one step.

Maybe the help page could be updated outlining the steps more clearly.

> BTW, In the help page it doesn't explain what it returns...

It is a side effect function - but yes, docs are missing a "return" entry.

**Comment by llrs** [comment]
Thanks for the detailed response. 

Couldn't the public-privat key pair be reused from other repositories? Or this should only be run once for each user? So usethis could check this and avoid suggesting it again.

I looked at the travis_get_var() and it opens two tabs, but it seems that the keys can't be reused from other repositories.

**Comment by pat-s** [comment]
@llrs I will do a major refactoring of the package which will result in a one-time API token query that will be stored on disk. No more browser window openings then.

**Comment by llrs** [comment]
Oh, great! I hope that this is not the single benefit of it. Thanks though

**Comment by pat-s** [comment]
Done. We now use API keys to authenticate.

**Comment by llrs** [comment]
Many thanks! And very well documented. I could set up my ~/.travis/travis.yml very fast. But I can't seem to use get_endpoint(). Should it be exported?

**Comment by pat-s** [comment]
@llrs Thanks for getting back.

`get_endpoint()` is for internal use only and is just to query the default endpoint depending on the approach the user took to set it. 

```r

get_endpoint <- function() {

  endpoint <- Sys.getenv("R_TRAVIS")
  return(endpoint)
}
```

Does this trigger confusion? I hoped that the doc in `?use_travis_deploy()` is descriptive enough.
What did you try to do with `get_endpoint()`?

**Comment by llrs** [comment]
Oh, no it is not confusing, but I expected that if the function is used to pass it to an argument that it would be available to the end user. (Otherwise I would set it the default to NULL and then call internally the function)

Somehow I managed to set up a repo on the travis-ci.com insted of the .org and I am not sure how it ended this way. 

I was checking the setup I had, and I saw it when I looked the help page of `browse_travis_token` but `browse_travis_token` didn't detect that this repo is using travis-ci.com (And in .Renviron I don't have any R_TRAVIS variable set). So I tried to call it to check which one detected.

**Comment by pat-s** [comment]
> Oh, no it is not confusing, but I expected that if the function is used to pass it to an argument that it would be available to the end user. (Otherwise I would set it the default to NULL and then call internally the function)

Yeah I see the potential confusion.
Maybe I should change this and handle it internally.

> I was checking the setup I had, and I saw it when I looked the help page of browse_travis_token but browse_travis_token didn't detect that this repo is using travis-ci.com (And in .Renviron I don't have any R_TRAVIS variable set). So I tried to call it to check which one detected.

Ok, mh. So in general `use_travis_deploy(endpoint = ".com")` should do it for COM, otherwise the default is always ORG unless set differently by env var `R_TRAVIS`.

If you can't reproduce, that's not a problem. Happy to take reports of any unwanted behaviour (optimally in a separate issue then). Thanks for reporting!
