### ISSUE TITLE
Unclear error message with invalid token

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#125]
If `.travis.yml` exists but has an invalid token, I saw the following with `use_tic()`:

```
── Setting up the CI providers. ──────────────────────────────────────────
Next we are getting the selected CI providers ready for deployment. This
requires some interaction with their API and you may need to create an
API token.

travis: Env var `R_TRAVIS` not set by user. Defaulting to '.org'
endpoint. If supplied, the `endpoint` argument in any `travis_*()`
function will take precedence. (This message is displayed once per
session.)

Error: lexical error: invalid char in json text.
                                       access denied
                     (right here) ------^
```

Can we detect this condition and give a clear error message?

**Comment by pat-s** [comment]
Do you mean `~/.travis/config.yml` instead of `.travis.yml`?
The latter should not have a token.

Was the error thrown by https://github.com/ropenscilabs/travis/blob/2419afb4b9fc5b8bcb57f01d8d174fd771171091/R/travis-auth.R#L93-L95?

**Comment by krlmlr** [comment]
I think the error comes from accessing the API.

**Comment by pat-s** [comment]
ah so we detect the token and get an error during the HTTP request due to an invalid token.

So in this case we should robustify the valid token detection? How can you even have an invalid token here? We check for character types and for the correct length. 🤔 

Can you maybe share the token which causes this error in private with me?

Maybe also the error only occurs due to some faulty extraction from `.travis/config.yml`? Does it also occur when you it via env var `R_TRAVIS_ORG`?

**Comment by krlmlr** [comment]
It was a stale token from the last decade. Fixing the config fixed the problem.

**Comment by pat-s** [comment]
Ah ok now I understand. Ok, we can check for a better error message in such cases.
