### ISSUE TITLE
Error when Travis CI not installed

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/travis#130]
I had not installed travis.com CI on my account but I set `R_TRAVIS` to ".com", and therefore got the not informative error

```r
 travis::travis_enable()
Error in UseMethod("status_code") : 
  no applicable method for 'status_code' applied to an object of class "NULL"
```

Could this somehow be documented better?

**Comment by pat-s** [comment]
Thanks!

Did you have set the API token via `R_TRAVIS_COM` before?
We stop early if the API key for the endpoint is not set.
Wondering a bit how you got through to the actual HTTP call 😄 

So assuming you had that one set: Do you mean by "not installed" the Travis CI app for your account?
Actually this one should not be needed for API requests.

**Comment by maelle** [comment]
Yes the key was there (it used not to be there in which case I got an http error).

""not installed" the Travis CI app for your account?" yes that's what I mean, after I did that I no longer got the error.

**Comment by pat-s** [comment]
Ok thanks, I'll try to replicate these scenarios on my machine.

Unfortunately we cannot really easily mirror such scenarios in the tests which is why such feedback is extremely valuable!

**Comment by pat-s** [comment]
- Deinstalled the Travis CI app and tried `travis_enable(endpoint = ".com")` on a few personal repos and got no error 🤔 . Maybe this only applies if one has never ever signed in into .com yet? Was this the case for you? The Travis CI app on GH should only be responsible for webhooks which show the build status of PRs. One should be able to make API calls unrelated from having this app installed (at least that is my current knowledge on it).

- If the API key is missing for the respective endpoint, I get

```r
x To interact with the Travis CI API, an API token is required. Please
  call `browse_travis_token()` first. Alternatively, set the API key
  via env vars `R_TRAVIS_ORG` or `R_TRAVIS_COM`.
Error: Travis API key missing.
```
  which is the expected behavior.

**Comment by maelle** [comment]
I had signed up, because I had the key.

I can't reproduce the http errors I got yesterday... I'll be more careful writing steps down next time, sorry!!

**Comment by pat-s** [comment]
No worries, thanks for reporting!
