### ISSUE TITLE
read_token() and edit_travis_config() point to different locations on windows 

### ISSUE THREAD

**Issue by FelixErnst** [ropenscilabs/travis#140]
Hi,

I tried to setup `travis` for work `pkgdown` and ran into several problems. Here is a kind of log. Maybe this help with future developments:

1. `read_token()` uses `readLines` internally, which with `~` expansion points to `C:\Users\user\Documents\.travis\`, wheras `edit_travis_config()` uses `edit_file()` internally, which opens a file at `C:\Users\user\.travis\`

2. The `config.yml` format is very very very weird and obscure. Any of these variants are invalid and do not work. Only the last option works, which is probably the least well formated version and requires exactly five space in front of the api key. Maybe using the `yaml` package might make things easier.
```
api.travis-ci.com/: XXX
```
```
api.travis-ci.com/:
  - XXX
```
```
api.travis-ci.com/:
  XXX
```
```
api.travis-ci.com/:
     XXX
```

Thanks for developing the package. Works find after navigating the setup phase.

Best
Felix

**Comment by pat-s** [comment]
Hi Felix,

yeah unfortunately Windows is always a bit off and we should probably use {rappdirs} internally. I haven't tested on Windows locally.

Your `config.yml` should be fine if you set it up automatically via the `travis` cli tool. I am not planning on adding additonal checks here as this is only the fallback option.
I recommend setting your token via the env var `R_TRAVIS_*`, respective to the endpoint you are using.

**Comment by FelixErnst** [comment]
Hi Patrick,

In my case I came in from `pkgdown` and the travis cli tool is not required nor mentioned either in this `travis` package nor in `pkgdown`. So I think it might worth thinking about it, since it is an integral part of using the package.

The 5 spaces think was really weird. `trimws` would also work instead of `strsplit(token, " ")[[1]][6]` https://github.com/ropenscilabs/travis/blob/3f4e59d33ff5dce9677594379fe56379cd637279/R/travis-auth.R#L100

**Comment by FelixErnst** [comment]
Or maybe better `trimws(gsub("-","",token))`, if the default config of the travis cli tool uses a config.yml with a dash.

**Comment by pat-s** [comment]
> In my case I came in from pkgdown and the travis cli tool is not required nor mentioned either in this travis package nor in pkgdown. 

It is not required because you can set the API key via the env var.
I do not understand yet how you ended up configuring `config.yml` manually? 
Also the Travis CLI tool is mentioned in the [Get Started vignette](https://docs.ropensci.org/travis/articles/travis.html).
How did you go down this route of using `config.yml` in the first place?

> So I think it might worth thinking about additional development in parsing the travis config, since it is an integral part of using the package.

I see your point but it has very little effect for lots of checks that would be required. Instead I would emphasize more to use the "env var" approach in the docs.

**Comment by FelixErnst** [comment]
Well, I used `usethis::use_pkgdown_travis()` as suggested in the `pkgdown` vignette. Running this leads to `travis::use_travis_deploy()`, which then leads me to the problem described above via `travis::browse_travis_token()`, if no config is detected, and further on to `travis::edit_travis_config()`.

So I had to figure out, which keyname was required (`api.travis-ci.com/` and not to forget the slash). Googling does not help (e.g. `travis-ci config.yml`), the format is not described in the `travis` package. So I dug though the code, stumbled over the different folders, which is not obvious from the code, except I expected weird stuff on windows. And the final kicker was figureing out, where the key is supposed to go in the yaml file.

The `env var` approach is only suggested as the second option, when going through this particular rabbit hole, via `travis::use_travis_deploy()` and `browse_travis_token()`

**Comment by pat-s** [comment]
Thanks. I updated the respective sections in the docs to emphasize the preference for env vars.

> the format is not described in the travis package

The format was described also beforehand in `?browse_travis_token()`.

I agree that quite some configuration is needed starting out from `usethis::use_pkgdown_travis()` but things are way more tedious if a user would have to go down this route completely alone without all the helpers here (this is how it was a long time).

I agree that the current version of the docs was sub-optimal and hope that things are now more clear. Thanks for reporting instead of silently being frustrated 👍

**Comment by FelixErnst** [comment]
Thanks for all the clarification. The structure of the config eluded me in `?browse_travis_token()` and I didn't `rtfm` til the end.
