### ISSUE TITLE
Combine efforts?

### ISSUE THREAD

**Issue by leeper** [ropenscilabs/travis#22]
Maybe we should combine efforts on this? https://github.com/cloudyr/travisci

**Comment by jeroenooms** [comment]
Hi Thomas!

 Our package is not an attempt to implement another travis client. We are working on a framework to for doing R stuff *on* travis. We are still in a prototyping phase and things are changing rapidly so we implemented everything in here. If it turns out later we can take advantage of `travisci` for some of the functionality, we might extract that. 

One thing that would be helpful is if you can make your package work with github oauth rather than user/password. That's where we got stuck.
