### ISSUE TITLE
Test more cases of org/repo ownership in the remake tests

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/travis#64]
Example:

- [ ] not member of the org, but admin of the repo
- [ ] org admin, but not admin of the repo
- [ ] org member + repo admin
- [ ] ...

**Comment by krlmlr** [comment]
Blocked by #77.

**Comment by pat-s** [comment]
Since we are authenticating via the Github login information, this should hopefully just work.

For most parts we use `github_user()$login` which defaults to the local user.

For tasks requiring permission for the repo, we use `github_info()$owner$login`.
If a request then is made from the "owner", it is automatically checked in the background via the HTTP request by the {gh} pkg if the local user has enough rights to apply the specific request.

I've had several different usecases already with personal/org + private/public repos and so far everything worked.
As long as we see no complains about something not working, I'd say that there is no need for complex tests?

**Comment by krlmlr** [comment]
Agreed. They didn't work well last time I checked.
